import type { CatalogTrackStub } from "./types";

export const MOCK_CATALOG: CatalogTrackStub[] = [
  // --- Beginner ---
  {
    id: "bundled-one-note",
    title: "One open low E",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "one-note.json",
    difficulty: "beginner",
    durationSec: 2,
    skillTags: ["timing", "single_note"],
    techniqueTags: ["alternate_picking"],
    targetBpm: 60,
    masteryAccuracyThreshold: 90,
  },
  {
    id: "bundled-chromatic",
    title: "Chromatic warm-up (0–4)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "chromatic-warmup.json",
    difficulty: "beginner",
    durationSec: 23,
    skillTags: ["timing", "fretting", "endurance"],
    techniqueTags: ["alternate_picking", "finger_independence"],
    prerequisiteTrackIds: ["bundled-one-note"],
    targetBpm: 72,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-major-scale",
    title: "E major scale — up & down",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "major-scale-e.json",
    difficulty: "beginner",
    durationSec: 10,
    skillTags: ["scales", "timing", "fretting"],
    techniqueTags: ["position_shift", "alternate_picking"],
    prerequisiteTrackIds: ["bundled-chromatic"],
    targetBpm: 76,
    masteryAccuracyThreshold: 85,
  },

  // --- Easy ---
  {
    id: "bundled-pentatonic",
    title: "Am pentatonic — up & down",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "pentatonic-am.json",
    difficulty: "easy",
    durationSec: 16,
    skillTags: ["scales", "single_note", "timing"],
    techniqueTags: ["position_shift", "alternate_picking"],
    prerequisiteTrackIds: ["bundled-major-scale"],
    targetBpm: 80,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-single-string",
    title: "Single string eighths (low E)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "single-string-eighths.json",
    difficulty: "easy",
    durationSec: 17,
    skillTags: ["rhythm", "timing", "single_note"],
    techniqueTags: ["alternate_picking"],
    prerequisiteTrackIds: ["bundled-one-note"],
    targetBpm: 92,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-open-chords",
    title: "Open chord changes (C–Am–Em–D)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "open-chords.json",
    difficulty: "easy",
    durationSec: 27,
    skillTags: ["chords", "rhythm", "timing"],
    techniqueTags: ["chord_switching"],
    prerequisiteTrackIds: ["bundled-single-string"],
    targetBpm: 76,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-spider",
    title: "Spider exercise (1-2-3-4)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "spider-exercise.json",
    difficulty: "easy",
    durationSec: 41,
    skillTags: ["fretting", "endurance", "timing"],
    techniqueTags: ["finger_independence", "alternate_picking"],
    prerequisiteTrackIds: ["bundled-chromatic"],
    targetBpm: 80,
    masteryAccuracyThreshold: 85,
  },

  // --- Intermediate ---
  {
    id: "bundled-arpeggio",
    title: "Arpeggio exercise (C–Em)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "arpeggio-c-em.json",
    difficulty: "intermediate",
    durationSec: 34,
    skillTags: ["arpeggios", "timing", "fretting"],
    techniqueTags: ["arpeggio_shapes", "position_shift"],
    prerequisiteTrackIds: ["bundled-open-chords"],
    targetBpm: 84,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-blues",
    title: "Blues shuffle riff (E)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "blues-shuffle.json",
    difficulty: "intermediate",
    durationSec: 22,
    skillTags: ["rhythm", "riffs", "timing"],
    techniqueTags: ["shuffle_feel", "alternate_picking"],
    prerequisiteTrackIds: ["bundled-single-string"],
    targetBpm: 88,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-power-chords",
    title: "Power chord rhythm (E–G–A–G)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "power-chords.json",
    difficulty: "intermediate",
    durationSec: 16,
    skillTags: ["chords", "rhythm", "riffs"],
    techniqueTags: ["power_chords"],
    prerequisiteTrackIds: ["bundled-open-chords"],
    targetBpm: 96,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-string-skip",
    title: "String skipping (open position)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "string-skipping.json",
    difficulty: "intermediate",
    durationSec: 32,
    skillTags: ["string_skipping", "fretting", "timing"],
    techniqueTags: ["string_skipping", "alternate_picking"],
    prerequisiteTrackIds: ["bundled-spider"],
    targetBpm: 82,
    masteryAccuracyThreshold: 85,
  },
  {
    id: "bundled-hammer-pull",
    title: "Hammer-on / pull-off drill",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "hammer-pull-drill.json",
    difficulty: "intermediate",
    durationSec: 17,
    skillTags: ["legato", "fretting", "timing"],
    techniqueTags: ["hammer_on", "pull_off"],
    prerequisiteTrackIds: ["bundled-spider"],
    targetBpm: 78,
    masteryAccuracyThreshold: 85,
  },

  // --- Advanced ---
  {
    id: "bundled-sustained",
    title: "Sustained melody (Am feel)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "sustained-melody.json",
    difficulty: "advanced",
    durationSec: 15,
    skillTags: ["single_note", "timing", "endurance"],
    techniqueTags: ["sustain_control", "position_shift"],
    prerequisiteTrackIds: ["bundled-arpeggio", "bundled-hammer-pull"],
    targetBpm: 74,
    masteryAccuracyThreshold: 88,
  },

  // --- Demo (embedded) ---
  {
    id: "demo-warmup",
    title: "Demo: ladder & sustain",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "demo",
    difficulty: "beginner",
    durationSec: 7,
    skillTags: ["timing", "single_note"],
    techniqueTags: ["alternate_picking"],
    targetBpm: 70,
    masteryAccuracyThreshold: 85,
  },

  // --- Premium previews ---
  {
    id: "premium-blues",
    title: "Blues turnaround in A",
    artist: "Catalog preview",
    tier: "premium",
    practiceChartKey: "none",
    difficulty: "advanced",
    skillTags: ["riffs", "rhythm"],
    techniqueTags: ["shuffle_feel", "power_chords"],
    targetBpm: 100,
    masteryAccuracyThreshold: 88,
  },
  {
    id: "premium-fingerstyle",
    title: "Fingerstyle étude No. 1",
    artist: "Catalog preview",
    tier: "premium",
    practiceChartKey: "none",
    difficulty: "advanced",
    skillTags: ["fretting", "timing"],
    techniqueTags: ["finger_independence", "sustain_control"],
    targetBpm: 84,
    masteryAccuracyThreshold: 90,
  },
];
