import type { CatalogTrackStub } from "./types";

export const MOCK_CATALOG: CatalogTrackStub[] = [
  // --- Beginner ---
  {
    id: "bundled-one-note",
    title: "One open low E",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "one-note.json",
    difficulty: "beginner",
    durationSec: 2,
  },
  {
    id: "bundled-chromatic",
    title: "Chromatic warm-up (0–4)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "chromatic-warmup.json",
    difficulty: "beginner",
    durationSec: 23,
  },
  {
    id: "bundled-major-scale",
    title: "E major scale — up & down",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "major-scale-e.json",
    difficulty: "beginner",
    durationSec: 10,
  },

  // --- Easy ---
  {
    id: "bundled-pentatonic",
    title: "Am pentatonic — up & down",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "pentatonic-am.json",
    difficulty: "easy",
    durationSec: 16,
  },
  {
    id: "bundled-single-string",
    title: "Single string eighths (low E)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "single-string-eighths.json",
    difficulty: "easy",
    durationSec: 17,
  },
  {
    id: "bundled-open-chords",
    title: "Open chord changes (C–Am–Em–D)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "open-chords.json",
    difficulty: "easy",
    durationSec: 27,
  },
  {
    id: "bundled-spider",
    title: "Spider exercise (1-2-3-4)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "spider-exercise.json",
    difficulty: "easy",
    durationSec: 41,
  },

  // --- Intermediate ---
  {
    id: "bundled-arpeggio",
    title: "Arpeggio exercise (C–Em)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "arpeggio-c-em.json",
    difficulty: "intermediate",
    durationSec: 34,
  },
  {
    id: "bundled-blues",
    title: "Blues shuffle riff (E)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "blues-shuffle.json",
    difficulty: "intermediate",
    durationSec: 22,
  },
  {
    id: "bundled-power-chords",
    title: "Power chord rhythm (E–G–A–G)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "power-chords.json",
    difficulty: "intermediate",
    durationSec: 16,
  },
  {
    id: "bundled-string-skip",
    title: "String skipping (open position)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "string-skipping.json",
    difficulty: "intermediate",
    durationSec: 32,
  },
  {
    id: "bundled-hammer-pull",
    title: "Hammer-on / pull-off drill",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "hammer-pull-drill.json",
    difficulty: "intermediate",
    durationSec: 17,
  },

  // --- Advanced ---
  {
    id: "bundled-sustained",
    title: "Sustained melody (Am feel)",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "bundled",
    bundledChartFile: "sustained-melody.json",
    difficulty: "advanced",
    durationSec: 15,
  },

  // --- Demo (embedded) ---
  {
    id: "demo-warmup",
    title: "Demo: ladder & sustain",
    artist: "Fretflow",
    tier: "free",
    practiceChartKey: "demo",
    difficulty: "beginner",
    durationSec: 7,
  },

  // --- Premium previews ---
  {
    id: "premium-blues",
    title: "Blues turnaround in A",
    artist: "Catalog preview",
    tier: "premium",
    practiceChartKey: "none",
    difficulty: "advanced",
  },
  {
    id: "premium-fingerstyle",
    title: "Fingerstyle étude No. 1",
    artist: "Catalog preview",
    tier: "premium",
    practiceChartKey: "none",
    difficulty: "advanced",
  },
];
